;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cider-load-current-buffer
        cleanup-buffer
        cljr-slash
        forward-sexp
        kill-region
        paredit-backslash
        paredit-backward
        paredit-backward-kill-word
        paredit-close-square
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp
        paredit-wrap-round
        sgml-slash
        smarter-move-beginning-of-line
        smex
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        cider-find-var
        cider-load-buffer
        cider-switch-to-repl-buffer
        helm-M-x
        indent-or-complete
        ))
