;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cider-load-current-buffer
	cleanup-buffer
	forward-sexp
	paredit-backward-kill-word
	paredit-forward-kill-word
	sgml-slash
	smex
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	))
