(source marmalade)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "s")
(depends-on "shut-up")

(depends-on "ace-jump-mode")
(depends-on "ack-and-a-half")
(depends-on "auto-complete")
;; (depends-on "auto-complete-css")
;; (depends-on "auto-complete-emacs-lisp")
;; (depends-on "auto-complete-etags")
;; (depends-on "auto-complete-ruby")
;; (depends-on "auto-complete-yasnippet")
(depends-on "auto-dictionary")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "dired-toggle-sudo")
(depends-on "elisp-slime-nav")
(depends-on "elnode")
;; (depends-on "emacs-color-theme-solarized-r0man")
;; (depends-on "emacs-request")
(depends-on "emms")
(depends-on "expand-region")
(depends-on "find-file-in-project")
(depends-on "flx")
;; (depends-on "gnus-notify")
(depends-on "haskell-mode")
;; (depends-on "haskell-mode-exts")
(depends-on "highlight-cl")
(depends-on "hive")
(depends-on "ido-vertical-mode")
;; (depends-on "inflect")
(depends-on "js2-mode")
(depends-on "macrostep")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multi-term")
(depends-on "multiple-cursors")
(depends-on "paredit")
(depends-on "popwin")
(depends-on "pretty-lambdada")
(depends-on "projectile")
(depends-on "ruby-mode")
(depends-on "ruby-test-mode")
(depends-on "rvm")
(depends-on "scss-mode")
(depends-on "slamhound")
(depends-on "smex")
(depends-on "smooth-scrolling")
(depends-on "vertica")
(depends-on "web-mode")
(depends-on "websocket")
(depends-on "yasnippet")
